enforce_secure_profile: false
listeners:
- query_port: 28477
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    bendiegames.replit.app: survival
  ping_passthrough: true
  priorities:
  - survival
  bind_local_address: false
  host: azurite.magmanode.com:27191
  max_players: 60
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 962f574d-6f3f-40f8-9b2a-2c0467a28290
player_limit: 60
ip_forward: true
groups: {}
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: true
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  server:
    motd: '&1Just another Waterfall - Forced Host'
    address: 127.0.0.1:25565
    restricted: false
  survival:
    motd: '&1Just another Waterfall - Forced Host'
    address: azurite.magmanode.com:27191
    restricted: false
